---
- debug: var=this_routing_zone

- name: List Routing Zones
  uri:
    method: GET
    headers: "{{ header_auth_json }}"
    url: "{{ aos_url }}/api/blueprints/{{ blueprint_id }}/security-zones"
    validate_certs: no
    return_content: yes
    status_code: 200
  register: routing_zones_return
  tags:
  - always
  - routing_zone_add

# - debug: var=routing_zones_return
#   tags:
#   - always
#   - routing_zone_add

# - name: debug items
#   debug: var=item
#   with_dict: "{{routing_zones_return.json['items']}}"

- name: Set routing_zone_id
  set_fact:
    routing_zone_id: "{{ item.value.id }}"
  with_dict: "{{routing_zones_return.json['items']}}"
  when: item.value.label == this_routing_zone.0.label

- debug: var=routing_zone_id
